name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Go Backend Tests
  go-backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: budget
          POSTGRES_USER: budget
          POSTGRES_DB: budget
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        cache: true
        
    - name: Install Go dependencies
      run: |
        cd budget
        go mod download
        go mod verify
        
    - name: Run Go linter
      uses: golangci/golangci-lint-action@v4
      with:
        working-directory: budget
        version: latest
        
    - name: Run Go tests
      run: |
        cd budget
        go test ./... -race -coverprofile=coverage.out -covermode=atomic
        
    - name: Upload Go coverage
      uses: codecov/codecov-action@v4
      with:
        file: budget/coverage.out
        flags: go-backend
        name: go-backend-coverage
        
    - name: Build Go binary
      run: |
        cd budget
        go build -o bin/budgetd ./cmd/budgetd
        
  # React Frontend Tests
  react-frontend:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: web/package-lock.json
        
    - name: Install frontend dependencies
      run: |
        cd web
        npm ci
        
    - name: Run ESLint
      run: |
        cd web
        npm run lint
        
    - name: Run frontend tests (if available)
      run: |
        cd web
        npm test --if-present
        
    - name: Build frontend
      run: |
        cd web
        npm run build
        
  # Integration Tests
  integration:
    runs-on: ubuntu-latest
    needs: [go-backend, react-frontend]
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: budget
          POSTGRES_USER: budget
          POSTGRES_DB: budget
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        cache: true
        
    - name: Run integration tests
      run: |
        cd budget
        PG_INTEGRATION=1 go test ./... -tags=integration -race
        
  # Security Scan
  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
